### ISSUE TITLE
Read posts color change

### ISSUE THREAD

**Issue by kejedi** [aeharding/voyager#1498] opened 2024-05-25 07:58 UTC
Would be nice if read posts went a gray color. Right now they just stay white (iOS) so I'm unsure what's read and what isn't.

**Comment by aeharding** [comment] 2024-05-25 09:49
The text should change color. Is that what you are referring to?

**Comment by aeharding** [comment] 2024-08-10 05:23
Closing because it should work! Otherwise if you can provide reproduction steps I will reopen.

**Closed by aeharding** 2024-08-10 05:23 UTC
Labels: enhancement
