### ISSUE TITLE
Clicking a community link navigates to the community, but does not reload the page.

### ISSUE THREAD

**Issue by InterstellarOne** [aeharding/voyager#527] opened 2023-07-26 00:46 UTC
This means that the community you were in still appears and only the header bar changes, so you will have scroll up to the top and reload the page to see posts from the linked community.

**Comment by aeharding** [comment] 2023-07-28 04:37
Do you have reproduction steps? Thank you!

**Comment by aeharding** [comment] 2023-11-19 01:14
Thanks for the report, however I'm closing due to no known reproduction.

**Closed by aeharding** 2023-11-19 01:14 UTC
Labels: reproduction-needed
