### ISSUE TITLE
Create new post button +

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1115] opened 2023-12-21 17:14 UTC
**Is your feature request related to a problem? Please describe.**
Its extremely difficult for someone who is new to how lemmy/reddit works to ever discover how to make a post when using Voyager because there is no visible button anywhere to create a post.

**Describe the solution you'd like**
I would love for there to be a + button that lets you fill in the title and enter a link image ir body text and then click next to select which community to post it in.

The current post workflow is:
The user has to know what community they will post in, then search for the community, then open the community, and then click the ..., then click the submit post, and then select between separate Photo, Link, or Text post buttons, then fill in the fields, and click post.

Alternatively we can have a similar workflow to how other apps (mastodon, instagram, reddit) works: Click +, fill in the appropriate fields, choose what community to post.

**Additional context**
Voyager is the best Lemmy app and much better than the official web ui. When new people are introduced to Lemmy they are most likely going to be recommended Voyager regardless of platform. Voyager making it easy for new people to contribute will help the non tech related communities and members be able to flourish as currently Lemmy is mostly used by very tech inclined people since its still a bit difficult for the average person.

**Comment by slrgt** [comment] 2023-12-21 17:58
Here's a mockup on how it could look. The + can be in the middle since creating posts is the center of the usecase of Lemmy and the part that helps Lemmy the most.

![image](https://github.com/aeharding/voyager/assets/114287507/10c5bae8-e4e7-453b-ae99-c1e63596a765)

The Profile section could be moved to the settings location of the navbar and include the profile options above the settings.

**Comment by aeharding** [comment] 2023-12-21 20:42
Thanks, but this is a duplicate of https://github.com/aeharding/voyager/issues/730

**Closed by aeharding** 2023-12-21 20:42 UTC
Labels: enhancement
