### ISSUE TITLE
Tapping on an image should mark it’s post as read

### ISSUE THREAD

**Issue by choltz** [aeharding/voyager#341] opened 2023-07-09 17:33 UTC
repro:
1. View a list of posts (pics for example)
2. Find an image post with an associated image and tap on the image, not the text of the post
3. At this point the image expands to fit the screen
4. Close the image

Expected results
The post associated with the image should be marked as read

Actual results
The post associated with the image is not marked as read.

**Comment by GitBarns** [comment] 2023-07-09 21:06
I think it's the same as https://github.com/aeharding/wefwef/issues/336

**Comment by Cheb89** [comment] 2023-07-09 22:08
This is something that bugs me to mo end, I hope it can be sorted

**Comment by aeharding** [comment] 2023-07-10 03:36
Marking as duplicate of #336

**Closed by aeharding** 2023-07-10 03:36 UTC
