### ISSUE TITLE
Blank screen for new Lemmy instance

### ISSUE THREAD

**Issue by Showfom** [aeharding/voyager#722] opened 2023-09-03 14:32 UTC
It's just a blank screen without any content shows on a new Lemmy instance [R.NF](https://r.nf/)

For example:

https://vger.app/posts/r.nf/all

**Comment by alexwasserman** [comment] 2023-09-03 23:51
Hey, are you seeing the same errors are #716?

**Comment by Showfom** [comment] 2023-09-04 00:20
Hi,

I didn't see any errors but just no content with the latest Lemmy 0.18.4-beta.8.

API and lemmy-ui are working fine.

**Comment by Showfom** [comment] 2023-09-04 00:25
Seems voyager is not working with latest Lemmy 0.18.4-beta.8

For example

https://m.lemmy.world/posts/lemmy.miichelle.moe/all
https://m.lemmy.world/posts/r.nf/all

Both instances are running on Lemmy 0.18.4-beta.8 but not working with voyager

**Comment by Showfom** [comment] 2023-09-04 23:50
Same issue from Photon but they have fixed it:

https://github.com/Xyphyn/photon/issues/140#issuecomment-1705720755

**Comment by alexwasserman** [comment] 2023-09-05 01:58
Thanks, @Showfom, I think this is a dupe of #716 , and I've submitted a PR to fix it: #723

**Comment by aperson** [comment] 2023-09-13 23:46
Beehaw must've updated lemmy a day or so ago because voyager now entirely blanks out when they're selected.

**Comment by aeharding** [comment] 2023-09-24 17:12
I believe this was fixed with the most recent patch!

**Closed by aeharding** 2023-09-24 17:12 UTC
