### ISSUE TITLE
[Native app 1.11.2] App crashes when trying to save images.

### ISSUE THREAD

**Issue by LawsuitLigament** [aeharding/voyager#714] opened 2023-08-27 11:00 UTC
https://github.com/aeharding/voyager/assets/140815477/dad5e7fe-be65-4ad0-9809-61d135018fbe

**Comment by sethmaxwl** [comment] 2023-08-30 20:25
I'm also seeing this happen a lot.

**Comment by RyanU1328** [comment] 2023-09-23 22:16
I have the same issue

**Comment by aeharding** [comment] 2023-09-24 17:08
Hi there! Is it happening for all images, or just certain ones? Can you please link the posts where this issue is happening? Also please provide android version.

Thanks

**Comment by RyanU1328** [comment] 2023-09-24 17:29
Hey,

Thanks for the message!

It happens for all images, occasionally it will work but usually only once then it fails again. App version 1.11.3. Android version 13.1 (OxygenOS if that makes a difference)

I can link images, but it would be a lot of links, do you want that?

Many thanks,

Ryan Urquhart
________________________________

**Comment by stschirky** [comment] 2023-10-17 07:20
I also have this issue. App version 1.15.2. It used to work sometimes but since some days it's always crashing.

**Comment by aeharding** [comment] 2023-10-17 21:46
Thanks! This should be resolved in the next release of Voyager. Turns out, Android has a crash after you save an image a ton of times (why are you the way you are, Android) which is why I couldn't initially reproduce

**Closed by aeharding** 2023-10-17 21:46 UTC
Labels: android, reproduction-needed

**Comment by RyanU1328** [comment] 2023-10-17 22:11
Thanks so much! The app is amazing, thank you for all you do
