### ISSUE TITLE
Unable to scroll after swiping back to previous page

### ISSUE THREAD

**Issue by r0mnic** [aeharding/voyager#18] opened 2023-06-26 03:22 UTC
Occasionally when returning to the home feed after opening a post, I’m unable to scroll until I switch to a different pane (search or settings etc)

**Comment by aeharding** [comment] 2023-06-26 03:27
Hi, thanks for reporting. Can you let me know device and browser? And please let me know if you determine a consistent reproduction.

**Comment by r0mnic** [comment] 2023-06-26 03:35
Running on Safari on iPhone 12 mini. I’m running the IOS 17 beta so it could be specific to that.

**Comment by aeharding** [comment] 2023-06-26 03:45
OK, great! I have a 13 mini so I'll keep an eye out.

**Comment by aeharding** [comment] 2023-06-26 03:47
One thing I have noticed potentially related to this, is that if you swipe back and then try to swipe down quickly after, if sometimes "captures" your swipe events until you wait >1 second without interaction. Then you can swipe down the feed again.

**Comment by PawanHegde** [comment] 2023-06-27 18:13
I can reproduce this on iPhone 12 running iOS 16.5.1. Seems to happen if i try a swipe very soon after finishing the first one.

**Comment by aeharding** [comment] 2023-06-27 21:01
I'm going to assume that this is just the bug where scrolling gets temporarily "stuck" trying to swipe down a feed after quickly swiping back from a post/etc.

I believe this is an Ionic bug. Still need to see if there's an existing upstream issue.

**Comment by MarkLindsay** [comment] 2023-06-30 03:52
For me, when scrolling stops working I engage a swipe gesture and then scrolling works again (like an up vote swipe, but you don’t even have to complete the gesture). Don’t know if that helps.

iOS 16.5.1, iPhone 13 Pro

**Comment by snickell** [comment] 2023-07-01 00:20
I've been trying to track this one down. I'm on an iPad.

I've only been able to intentionally repro (when connected to a mac to get access to devtools) a few times after a lot of trying, but I suspect it may be caused or related to not clearly visible text being selected. Doing a careful "deselect press" in a blank part of the page consistently freed me from the lock.

Selecting text in the header (e.g. selecting the "Back" link/text) seems to (in ??? circumstances) cause a similar behavior... somehow further scroll and click events?

**Comment by aeharding** [comment] 2023-08-07 22:05
This is resolved with the native app. Because there is an upstream bug for Safari regarding the PWA, I'm closing this out :)

**Closed by aeharding** 2023-08-07 22:05 UTC
Labels: iOS, blocked, ionic-bug
