### ISSUE TITLE
Wrong message displaying after mod deletes a comment without a reason

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1389] opened 2024-04-04 03:46 UTC
**Describe the bug**
When a mod deletes a messages, instead of saying "deleted by mod" it is saying that the user deleted it themselves 

**To Reproduce**
As a mod, delete a user message without a reason

**Expected behavior**
Once the message is deleted it should say that it was deleted by the mod 

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/104597302/12730573-2c42-46a7-b029-c5913e99f7c4)

It is saying that this user deleted their own comment, which they didn't . I did as a mod.

**Comment by sallyFoster** [comment] 2024-04-06 01:11
@aeharding I thought of that too, but then I checked the mod log and the only entry was of me deleting the message.

**Comment by aeharding** [comment] 2024-04-06 02:39
That is what I would expect. If a user deletes their own message, that isn't shown in the modlog.

**Comment by aeharding** [comment] 2024-04-13 00:26
Closing since I believe this is expected behavior.

**Closed by aeharding** 2024-04-13 00:26 UTC
Labels: bug, waiting-on-response
