### ISSUE TITLE
Comment Search - Find on Page

### ISSUE THREAD

**Issue by QuarterSwede** [aeharding/voyager#785] opened 2023-10-15 22:18 UTC
Apollo had the ability to search comments via iOS’s Find on Page functionality. Would love to see that functionality back now that Lemmy is growing (last thread I looked at had 150+ comments).

**Comment by aeharding** [comment] 2023-10-15 23:25
Thanks, this is a duplicate of #609

**Closed by aeharding** 2023-10-15 23:25 UTC
