### ISSUE TITLE
When collapsing a comment it should scroll to the top of the collapsed comment.

### ISSUE THREAD

**Issue by brandon-a** [aeharding/voyager#508] opened 2023-07-22 17:57 UTC
When collapsing a particularly long comment when you are toward the bottom of the comment you end up much further down in the comments thread than the same or next comment. Typically reading the next comment is desired after collapsing so it would be better if when a comment is collapsed if the client can scroll to the collapsed comment so the subsequent comments are easy to get to without scrolling back up.

**Comment by rsammelson** [comment] 2023-07-22 19:41
I think this is a duplicate of #2

**Closed** 2023-07-23 01:42 UTC
