### ISSUE TITLE
Add Quick Format Buttons Above Keyboard Drawer

### ISSUE THREAD

**Issue by Corb3t** [aeharding/voyager#401] opened 2023-07-12 14:03 UTC
It would be nice if there were some quick format buttons in Voyager when one is commenting or creating a post and the keyboard drawer is being displayed. 

I’ve included a couple screenshots of apps that have similar functionality. 

Quick format items that could be included:
- Bold
- Italics
- Strikethrough
- Links
- Photo
- Lists

Voyagers existing keyboard drawer:
![image](https://github.com/aeharding/voyager/assets/43692728/f20badbe-e2e5-4eba-a33f-6ce0d5545278)

Memmy’s keyboard drawer:
![image](https://github.com/aeharding/voyager/assets/43692728/1716c7e8-6ea1-4a53-83d8-e6a40429e067)

GitHub’s keyboard drawer (my favorite - swipe right for more gestures!): 
![image](https://github.com/aeharding/voyager/assets/43692728/d7f04f54-2737-4816-83e1-48db054b83d8)

Document for Lemmy comment format (Markdown!): https://join-lemmy.org/docs/users/02-media.html

**Comment by aeharding** [comment] 2023-07-12 14:43
Thanks for the pictures, I believe this is a duplicate of #367 though

**Closed by aeharding** 2023-07-12 14:43 UTC
