### ISSUE TITLE
Add support to open other instance link in voyager

### ISSUE THREAD

**Issue by tzutoo** [aeharding/voyager#606] opened 2023-08-06 02:54 UTC
Add support for opening links to other instances in app instead of using the browser e.g. https://qlemmy.com/post/215583

**Comment by Benny-Git** [comment] 2023-08-08 06:08
I believe this is a must-have to make lemmy feel more reddit-like.

**Comment by aeharding** [comment] 2023-08-10 18:02
Duplicate of #235 :)

**Closed by aeharding** 2023-08-10 18:02 UTC
