### ISSUE TITLE
Show user avatars and bios on user pages

### ISSUE THREAD

**Issue by CoffeeCoder1** [aeharding/voyager#645] opened 2023-08-11 21:34 UTC
I would like to see user avatars and bios shown on user pages, and if it is possible to fit it in also show the banner (perhaps the banner would only show up if you have a large enough display, and the bio would be truncated or completely hidden and only accessible via the menu depending on screen size).

**Comment by aeharding** [comment] 2023-08-14 14:49
Marking as a duplicate of #457, we can track bio there too.

**Closed by aeharding** 2023-08-14 14:49 UTC
