### ISSUE TITLE
Show hidden posts in communities

### ISSUE THREAD

**Issue by bjoern-tantau** [aeharding/voyager#1131] opened 2024-01-02 17:44 UTC
When I select a community I would like to see all posts, even those I have read in my feed. I thought the feature to disable auto hide in communities would achieve this, but I think I misunderstood it.

I think the best way to solve this would be either the option to show hidden posts in communities or a general Show Hidden Posts. button in the context menu. The latter would help if someone wanted to get back to a post they saw in their feed but where they can't remember what community it was posted in.

**Comment by aeharding** [comment] 2024-01-03 23:25
I think I'm going to close this as a duplicate of #912.

**Closed by aeharding** 2024-01-03 23:25 UTC
Labels: enhancement

**Comment by pheerai** [comment] 2024-09-25 16:56
Given that #912 was implemented in a way that completely resets the read status (which is explicitly not what was asked for here), I think this should be reopened?
