### ISSUE TITLE
Option to enable avatars

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1273] opened 2024-03-03 00:44 UTC
**Is your feature request related to a problem? Please describe.**
I like seeing avatars and would like to be able to enable them on Voyager

**Describe the solution you'd like**
A setting that enables avatars to the left of the comment

**Comment by aeharding** [comment] 2024-03-03 00:51
Hi there! This is duplicate of https://github.com/aeharding/voyager/issues/567, please follow there

**Closed by aeharding** 2024-03-03 00:51 UTC
Labels: enhancement
