### ISSUE TITLE
No way to get back to main feed from Communities view

### ISSUE THREAD

**Issue by GitBarns** [aeharding/voyager#52] opened 2023-06-29 00:30 UTC
This one's pretty annoying, basically if you browse the main feed and somehow press "back" by accident or click the top left Communities button, there's no way to get back to where you were in the main feed. Pressing "Back" again will exit the app... 

One option would be to make the bottom Posts button reopen the main feed where it was.

Repro: open app, click on Communities and pick one, scroll around/click around, press back, and your "stuck" in Communities

**Comment by aeharding** [comment] 2023-06-29 00:31
What's your device model and version? I can't reproduce this.

**Comment by GitBarns** [comment] 2023-06-29 00:32
Another solution can be to allow the Communities View to be swiped left i.e. Hide it back

**Comment by GitBarns** [comment] 2023-06-29 01:08
> What's your device model and version? I can't reproduce this.

Android Samsung s22, but I'm pretty sure this happens on any android

**Comment by mrmikeface** [comment] 2023-07-03 05:03
I think this is a duplicate of aeharding/wefwef#91 or vice versa

**Comment by huanga** [comment] 2023-07-03 08:58
Not duplicate. This seems like a bug that results in the user being stuck in a view — I’ve never encountered it myself — where as the other one is a feature improvement.

**Comment by aeharding** [comment] 2023-08-14 14:42
Closing since I cannot reproduce. Feel free to open a new issue if a reproduction is found.

**Closed by aeharding** 2023-08-14 14:42 UTC
Labels: reproduction-needed

**Comment by morhei** [comment] 2024-06-13 07:22
I havw the same issue. It happens for me, when I am in my home feed and I hit 'back'. Then the communities drawer opens and from there I can only select a community, home, or all, or hit 'back' again which closes the app.
If I select home I get put back to the top instead of where I have been.

**Comment by nafiz1001** [comment] 2024-11-24 16:33
When I use the web version (`pnpm run dev`), I can go back to the main feed by clicking on the same community the main feed is currently visiting. Ideally there should be a back button for that, but I don't see any.
![image](https://github.com/user-attachments/assets/2b1700f2-a850-4b9f-9d86-7837d4861997)

On the Voyager version 2.18.2 on my Android 9, it seems to refresh the main feed regardless of which community I visited. Back button does not work either; it just moves to another tab or closes the app.
