### ISSUE TITLE
No way to save an image posted in comments via the app

### ISSUE THREAD

**Issue by adarsh1001** [aeharding/voyager#1110] opened 2023-12-20 14:27 UTC
**Is your feature request related to a problem? Please describe.**
If there is an image posted in the comments, there is no way to save (download) it if one is using the app.

**Describe the solution you'd like**
A way to save images posted in comments via the app. Either via the 3-dot comment menu or in the image viewer that comes up when we click on the image.

**Describe alternatives you've considered**
Opened the web app and saved the image.

**Additional context**
Applies to GIFs posted in comments as well.

**Comment by aeharding** [comment] 2023-12-20 16:20
Thanks, this is a duplicate of https://github.com/aeharding/voyager/issues/1090

**Closed by aeharding** 2023-12-20 16:20 UTC
Labels: enhancement
