### ISSUE TITLE
Unreadable Status Bar in Light Mode

### ISSUE THREAD

**Issue by kwmc-lucas** [aeharding/voyager#44] opened 2023-06-28 07:27 UTC
The time, battery indicator etc. are White, regardless of whether the device is in Light or Dark Mode.

The text (and icons) should be Black when in Light Mode, and White when in Dark Mode.

**Comment by aeharding** [comment] 2023-06-28 16:43
This is tricky. We can force it to be white, but then it won't be translucent which means that dialogs open won't look right.

This is an unfortunate limitation of iOS PWAs. I *think* there's a way to get around it by dynamically switch header modes, but this isn't a super quick fix.

https://social.harding.dev/@alex/110590855343602954

**Comment by valentind44** [comment] 2023-07-01 11:41
Indeed there is no way to have translucent statusbar with black text 😞 

But solid statusbar
```html
<meta
      name="apple-mobile-web-app-status-bar-style"
      content="default"
    />
```
is still better than having white text on white background when using light mode.

I've used the ["Run JavaScript on Webpage" Shortcus action](https://support.apple.com/guide/shortcuts/use-the-run-javascript-on-webpage-action-apdb71a01d93/ios) to execute the following code inside wefwef.app:
```js
document.querySelector("meta[name=apple-mobile-web-app-status-bar-style]").setAttribute("content", "default")
completion(true)
```
then installed it to my home screen, until we have a better solution (if that can help anyone in the same case)

![wefwef_light](https://github.com/aeharding/wefwef/assets/14093922/b1093642-6de4-432b-afb3-da5ad459270b)

**Comment by aeharding** [comment] 2023-07-01 19:27
Yeah, the problem is it looks bad with dialogs and also makes the available vertical space of dialogs less.

**Comment by kwmc-lucas** [comment] 2023-07-03 10:45
@aeharding can you honestly say that the way it looks now - constantly having the core UI of the device unreadable - is _worse_ than a solid status bar when showing dialogs?

**Comment by aeharding** [comment] 2023-07-03 15:49
It's not just a solid status bar. Dialogs get shifted down from ionic, providing less vertical space for writing comments and logging in. That's the concern with @valentind44's approach.

Please, reach out to Apple about this.

**Comment by kwmc-lucas** [comment] 2023-07-03 15:57
@aeharding thanks Alex, I think you saw my Mastadon post, so hopefully that helps!

Is this definitely an Apple issue, and not Ionic?

**Comment by aeharding** [comment] 2023-08-05 22:09
Yes, it's 100% an apple issue. I am closing since it is resolved with the native app that has the ability to control status bar style. :)

Once Apple fixes their broken PWA support this can be reopened.

**Closed by aeharding** 2023-08-05 22:09 UTC
Labels: iOS, blocked
