### ISSUE TITLE
Add ability to cross-post

### ISSUE THREAD

**Issue by cwallace** [aeharding/voyager#84] opened 2023-06-30 04:55 UTC
It would be really nice to have a button when clicked inside a post to cross post the link to another community.  Maybe next to the upvote, downvote and save buttons?

**Comment by BarterClub** [comment] 2023-07-27 16:42
Yes please

**Comment by fievel** [comment] 2023-08-05 18:53
Indeed it's one of the rare reasons I have to switch back and forth between voyager and Lemmy standard web UI

**Comment by sallyFoster** [comment] 2023-12-12 03:39
@0xCmdrKeen Would you be interested in working on this feature? 

This is literally the feature that I have been waiting for the most. For some reason no Lemmy app has it. Therefore, since I constantly cross post, I need to be switching to the browser a lot. It would be super great if you wanted to make this feature happen since you have implemented several features so far.

**Comment by 0xCmdrKeen** [comment] 2023-12-12 07:04
@sallyFoster I'll consider it, although it's not something I personally use or need.

Does anyone here have screenshots of how this was implemented in Apollo or remember what icon that used? Like I said, it's not something I do a lot but I think it just asked for the community and then made a post with the same title and a link to the original.

Looking at the original Lemmy client, it appears that clicking the crosspost button there instead simply opens a "create new post" form that has every field pre-filled with the respective values from the original post, except for the community. 

What would this ideally look like in Voyager? The post editor currently doesn't have an input for community because it can only be invoked from the community screen. I see at least a few possibilities here:

1. Prompt user for community to crosspost to and create a new link post with the same subject line as the original post
2. Prompt user for community and show the post editor pre-filled with the values from the original post
3. Prompt user for community and immediately just create a duplicate of the original post there
4. Add a community input to the post editor and show the editor with all other values copied from the original

Option 1 would be closest to Apollo (I think), option 4 would be closest to the Lemmy web client. Also would like to hear @aeharding's opinion on this.

**Comment by 0xCmdrKeen** [comment] 2023-12-12 07:51
Looking through the [available icons](https://ionic.io/ionicons), here are some that I found that might be appropriate for this feature:

|Name|Icon|
|---|---|
|`duplicate-outline` |<img width=32 height=32 alt="duplicate-outline" src="https://github.com/aeharding/voyager/assets/98132670/55beb10b-7df0-4eb2-a958-33d1942baabb">
|`repeat-outline`|<img width=32 height=32 alt="repeat-outline" src="https://github.com/aeharding/voyager/assets/98132670/c855e8cc-1992-42a4-a7c4-fa5edb1bd8aa">
|`enter-outline`|<img width=32 height=32 alt="enter-outline" src="https://github.com/aeharding/voyager/assets/98132670/0635ad9d-3d20-4962-af91-90e759a85a48">
|`exit-outline`|<img width=32 height=32 alt="exit-outline" src="https://github.com/aeharding/voyager/assets/98132670/6c76dcb0-0e8c-4be7-a2f4-670e85c7fb35">
|`push-outline`|<img width=32 height=32 alt="push-outline" src="https://github.com/aeharding/voyager/assets/98132670/311198ff-3cde-45e4-a9b1-45e0a0d82e5d">
|`share-social-outline`|<img width=32 height=32 alt="share-social-outline" src="https://github.com/aeharding/voyager/assets/98132670/e1f5142d-bd8f-4b8d-8593-fdb5419e987b">

**Comment by 0xCmdrKeen** [comment] 2023-12-12 11:44
Okay, after doing all of this brainstorming I felt inspired and actually went ahead and gave it a try. I went with option 2 and made something that I think is an adequate combination of Apollo and the Lemmy web client. PR incoming.

**Comment by sallyFoster** [comment] 2023-12-18 18:00
@0xCmdrKeen I am super sorry that you had to do all that work because I asked you for the feature. I was not aware of the working structure of collaborations. I just thought that nobody else had time to implement it and that is why it was idle for months. I am super sorry 😭.

**Comment by 0xCmdrKeen** [comment] 2023-12-18 18:32
@sallyFoster no worries. I was a little disappointed of course, but I'm not upset since it was an interesting challenge anyways. And I also missed the fact that Alex had already assigned it to himself, but as the project owner we gotta respect his decisions.

**Closed** 2024-01-11 00:47 UTC
Labels: enhancement, parity:lemmy, parity:apollo
