### ISSUE TITLE
Scrolling doesn't work while a GIF is on the screen

### ISSUE THREAD

**Issue by DaveAlton** [aeharding/voyager#602] opened 2023-08-05 19:18 UTC
When scrolling the home timeline, find a GIF. When dragging your finger to, it can't start from where the GIF is showing, otherwise the scrolling doesn't work. When a large GIF appears in the timeline, there's no way to scroll past it.

**Comment by aeharding** [comment] 2023-08-05 21:52
Can you please provide a reproduction? Also try restarting your phone and see if that helps. Thanks!

**Comment by DaveAlton** [comment] 2023-08-06 16:06
Restarting doesn't help. 

1. Go to !gifs@lemmy.world
2. Scroll until you find a GIF that autoplays on the timeline. 
3. Notice where your finger touches the timeline when it scrolls. 
4. Have your finger touch the animated gif when it starts scrolling. Touch and drag up from the gif to scroll down the timeline. 
5. The timeline doesn't scroll.

**Comment by CDeLeon94** [comment] 2023-08-25 18:52
I'm having very sporadic issues scrolling images too. I'm having trouble reproducing it consistently, but it seems related to accidental gesture activation, maybe the posts aren't being reset to center after a partial side swipe. It seems additional sliding of posts left/right can help unstick the scrolling issue.

**Comment by CDeLeon94** [comment] 2023-08-25 18:58
Gifs that are struggling to load also seem to not allow you to scroll when you initiate the scroll by starting the touch on top of the gif

**Comment by damianvila** [comment] 2023-09-20 12:01
Same behaviour as @DaveAlton here.

iPhone 11 Pro.
iOS 17.0
Voyager 1.11.3

- Open !gifs@lemmy.world
- Scroll to an autoplay GIF
- Try to scroll by touching the region inside the GIF, the screen won't scroll (works outside the playing GIF).

Seems like the GIF is capturing the events, and not bubbling it upwards, to allow scrolling.

**Comment by al-e-borland** [comment] 2023-09-21 01:11
I have this issue as well. The issue isn’t gifs, the issue is with videos (which people call gifs now when they don’t have audio auto-playing). This is why the issue seems intermittent. I can scroll over .gif images. I can not scroll over what is likely a .mp4 video.

**Comment by aeharding** [comment] 2023-09-22 18:12
Hello! Looks like this will be solved with https://github.com/WebKit/WebKit/pull/18081 in a future iOS release. I looked into this briefly and I couldn't find an easy workaround.

**Comment by aeharding** [comment] 2023-10-13 16:14
Confirmed resolved in iOS 17.1 beta 3.

**Comment by aeharding** [comment] 2023-10-26 17:43
For some reason, this was fixed in 17.1 beta 3 but is not fixed in the final 17.1 release 😤

**Comment by aeharding** [comment] 2023-10-29 02:21
I added a workaround in the latest release. It doesn't work perfectly, but at least you should be able to scroll out of a video that appears on your feed. Waiting on Apple for the official fix.

**Closed by aeharding** 2023-10-29 02:21 UTC
Labels: iOS
