### ISSUE TITLE
[Feature request] Backup and restore settings

### ISSUE THREAD

**Issue by PyroGenesis** [aeharding/voyager#783] opened 2023-10-15 01:12 UTC
The ability to backup and restore my settings would be useful. 

I've come across a situation where I have to reinstall Voyager but I don't want to set it up from scratch again.

**Comment by boozook** [comment] 2023-10-28 23:39
I suppose sync just cfg file in app-sandbox/Documents with iCloud could be enough.

**Comment by aeharding** [comment] 2023-10-29 02:08
Duplicate of #366

**Closed by aeharding** 2023-10-29 02:08 UTC
Labels: enhancement
