### ISSUE TITLE
Crash when opening inbox

### ISSUE THREAD

**Issue by XCraftMC23** [aeharding/voyager#950] opened 2023-11-17 22:23 UTC
### Crash description

I opened my inbox and it crashed.
I'm on iOS 17 beta 3

### Device and app metadata

  - window.location.href: `capacitor://localhost/`
  - react-router location.pathname: `/inbox/all`
  - Logged in? `true`
  - Native app? `true`
  - Installed to home screen? `true`
  - Voyager version: `1.23.2`
  - BUILD_FOSS_ONLY: `false`
  - User agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

### Crash data

Error: `TypeError: undefined is not an object (evaluating 'e.linked.filter')`

#### Stack trace

```
@capacitor://localhost/index.js:216:190067
d@capacitor://localhost/index.js:209:48939
@capacitor://localhost/index.js:209:50120
d@capacitor://localhost/index.js:209:48939
l@capacitor://localhost/index.js:232:439
useSyncExternalStore@capacitor://localhost/index.js:40:70954
@capacitor://localhost/index.js:232:717
@capacitor://localhost/index.js:232:1664
om@capacitor://localhost/index.js:248:111873
H1e@capacitor://localhost/index.js:248:114598
B5@capacitor://localhost/index.js:40:63935
u7@capacitor://localhost/index.js:40:116540
l7@capacitor://localhost/index.js:40:112269
DK@capacitor://localhost/index.js:40:112197
rb@capacitor://localhost/index.js:40:112050
sk@capacitor://localhost/index.js:40:108412
a8@capacitor://localhost/index.js:40:109219
fl@capacitor://localhost/index.js:40:47676
uc@capacitor://localhost/index.js:40:109667
@capacitor://localhost/index.js:248:213293
@capacitor://localhost/index.js:248:209616
forEach@[native code]
B@capacitor://localhost/index.js:248:209597
@capacitor://localhost/index.js:248:211914
```

**Comment by aeharding** [comment] 2023-11-18 02:19
Hi there. I think this is a duplicate of #935 and should hopefully be resolved next release :)

**Closed by aeharding** 2023-11-18 02:19 UTC
