### ISSUE TITLE
Sort option disappears when using "top" option in "pumpkin" theme.

### ISSUE THREAD

**Issue by dobbsrx** [aeharding/voyager#577] opened 2023-08-02 22:34 UTC
![image](https://github.com/aeharding/voyager/assets/69364019/91af3179-1e7c-41ea-ab34-9a5e30c0fa5a)

![image](https://github.com/aeharding/voyager/assets/69364019/27ced71a-9b24-4a20-a520-8a57cca0727b)

**Comment by dobbsrx** [comment] 2023-08-02 22:40
You can still click the blank spot and it will bring up the sort menu, as in the picture above. All other options (HOT, ACTIVE, NEW, Most/New Comments) keep the icon visible in the corner; however, any of the top options (Hours, 6, 12, Day, etc) the icon disappears. After testing, it seems to be the same in all the other themes as well (Default, Fiero, etc)

**Comment by dobbsrx** [comment] 2023-08-02 22:44
Iphone 12, 16.5.1, PWA, Voyager Docker 1.2.0

**Comment by aeharding** [comment] 2023-08-05 22:00
Interesting but I'm unable to reproduce. Can you try restarting the app and/or your phone? Thanks

**Comment by aeharding** [comment] 2023-08-05 22:01
Actually, I believe the underlying issue is #576 so I am closing in favor of that. Thanks again!

**Closed by aeharding** 2023-08-05 22:01 UTC
Labels: reproduction-needed
