### ISSUE TITLE
[ANDROID] BUG: Tapping the bottom of the screen scrolls down by a certain amount, causing scrolling issues

### ISSUE THREAD

**Issue by Juansero29** [aeharding/voyager#612] opened 2023-08-06 21:36 UTC
It's exactly what the title says. It's been there since Android app release officially. However is present both in the PWA and the official app. Whenever I scroll down there's a chance the screen just bugs and interpret it as tapping a sort of invisible button in the bottom of the screen that makes the whole app scroll down by ~2 posts.

**Comment by aeharding** [comment] 2023-08-07 02:21
Hi there! Yes, unfortunately this is an Ionic bug. See https://github.com/ionic-team/ionic-framework/issues/21982. Closing as duplicate of #287.

**Closed by aeharding** 2023-08-07 02:21 UTC
