### ISSUE TITLE
Bug: exiting web view on Android causes bottom bar to briefly freak out

### ISSUE THREAD

**Issue by aperson** [aeharding/voyager#371] opened 2023-07-11 01:02 UTC
Sorry I didn't enable showing my taps, but you can see that when exiting a WebView, the bottom bar freaks out:

https://youtu.be/oi-p4P1_8zk

Edit:

It even did it when I exited out from following this GitHub's link in-app.

**Comment by mdecourcy** [comment] 2023-07-11 01:35
Do you have your default system webview changed, or are you on default webview?

I'm on Android 13 with vanadium as my default webview, and haven't experienced this behavior

**Comment by aperson** [comment] 2023-07-11 01:42
Default.  I am on stock android 13 on a pixel 7 pro.

**Comment by mdecourcy** [comment] 2023-07-11 02:35
Just noticed it, using chromium on android 13.

Has this always been an issue for you, or was this behavior only apparent after a recent release @aperson

**Comment by aperson** [comment] 2023-07-11 02:37
Only just noticed it when updating to 0.18.3.

**Comment by aeharding** [comment] 2023-07-12 04:04
I would appreciate anyone that can take the time to checkout 0.18.0 (or whatnot) and verify if this is indeed a regression

**Comment by mdecourcy** [comment] 2023-07-12 04:40
https://youtube.com/shorts/Qc3RjM7MbM4?feature=share

**Comment by aeharding** [comment] 2023-07-12 04:49
It looks like some glitching of the footer did happen at the end there?

**Comment by mdecourcy** [comment] 2023-07-12 04:57
Yeah, last two look slightly buggy. I honestly didn't notice it until this issue was submitted.

**Comment by aeharding** [comment] 2023-07-20 19:09
I'm going to close this because I believe it is a browser bug

**Closed by aeharding** 2023-07-20 19:09 UTC
Labels: bug, help wanted

**Comment by mdecourcy** [comment] 2023-07-21 02:09
@aeharding I agree, bug isn't there on FF mobile.
