### ISSUE TITLE
Keyboard Input in Browser

### ISSUE THREAD

**Issue by FriederHannenheim** [aeharding/voyager#738] opened 2023-09-18 10:20 UTC
Hey. Lemmy is a great app. I use it in my Desktop browser and I would really appreciate being able to use things like the arrow keys for scrolling or backing out of posts.

**Comment by aeharding** [comment] 2023-09-24 17:17
Thanks! Closing as duplicate of #738

**Closed by aeharding** 2023-09-24 17:17 UTC

**Comment by FriederHannenheim** [comment] 2023-09-24 19:00
Sorry. I believe you have made an error. This issue is #738

**Comment by aeharding** [comment] 2023-09-24 19:44
Sorry #733 :)
