### ISSUE TITLE
Back button text overflow

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#587] opened 2023-08-04 09:19 UTC
![image](https://github.com/aeharding/voyager/assets/20093825/36e97872-015a-409f-b0d4-dcb77bc9dbd9)

Overflow of the title itself is handled correctly, but not for the back button which can be quite lengthy

**Comment by aeharding** [comment] 2023-08-04 21:27
Duplicate of #313

**Closed by aeharding** 2023-08-04 21:27 UTC
