### ISSUE TITLE
[Bug] Community icon is too small in menu

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#533] opened 2023-07-27 17:00 UTC
![image](https://github.com/aeharding/voyager/assets/723314/117f0d35-b0da-4c03-aeb4-8df0d6201dc9)

As seen in the image, the icon for the community is much smaller then expected. My guess is due to the length of the community name plus the instance name.

Haven’t seen it but it’s possible it could also affect the username if the name and the instance is also long.

Voyager 1.0.1
Safari 
iOS 17 Developer Beta 2

**Comment by aeharding** [comment] 2023-07-28 04:35
Thanks, I think I'll consider this a duplicate of #271 since it will get fixed with that!

**Closed by aeharding** 2023-07-28 04:35 UTC
