### ISSUE TITLE
Swipe to go Forward

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1118] opened 2023-12-21 23:19 UTC
**Is your feature request related to a problem? Please describe.**
When swiping away from a post and scrolling sometimes you want to go back to the post you had opened.

**Describe the solution you'd like**
It would be great to be able to swipe to go "Forward" like how Apollo did jt and how Avelon does it.

![image](https://github.com/aeharding/voyager/assets/114287507/6fc06106-928a-4770-8330-133b8dab11f4)

**Comment by aeharding** [comment] 2023-12-21 23:29
Duplicate of https://github.com/aeharding/voyager/issues/91

**Closed by aeharding** 2023-12-21 23:29 UTC
Labels: enhancement
