### ISSUE TITLE
The “New Account” indicator 👶 can be made to show a large negative number

### ISSUE THREAD

**Issue by owlboy** [aeharding/voyager#947] opened 2023-11-17 11:14 UTC
**Describe the bug**
It appears people can falsify account data to have creation dates in the future. This leads to a large negative number appearing next to the new account icon.

**Example Account/Comment:** 
https://lemmy.tgxn.net/comment/667643

![IMG_2864](https://github.com/aeharding/voyager/assets/237349/195dcf97-f592-46e8-8093-df2baa60fe2c)

**Comment by aeharding** [comment] 2023-11-17 14:10
Thanks for the report! This is a duplicate of #914

**Closed** 2023-11-17 14:10 UTC
Labels: bug
