### ISSUE TITLE
Bug: Unable to login to Lemmy with an admin account

### ISSUE THREAD

**Issue by FlamingKeyboard** [aeharding/voyager#263] opened 2023-07-04 21:38 UTC
Hello, I recently created my own lemmy instance, and could not login to the instance using wefwef with my instance's admin credentials. I created a new user account on the same instance and was able to successfully log in.

**Comment by aeharding** [comment] 2023-07-04 21:42
Hi,

Can you please open inspector and let me know what fails?

Thanks!

**Comment by bdonvr** [comment] 2023-07-04 23:03
Not able to reproduce. Works fine for me on my v0.18.0 instance

**Comment by FlamingKeyboard** [comment] 2023-07-05 04:23
Just checked inspector, a 400 error is returned and then throws along with "Uncaught (in promise) password_incorrect". Same exact credentials authenticate successfully on the lemmy itself.
Tried the login on another iOS app and failed to authenticate only on the admin account for that as well.
Could just be something to do with my instance, is there some configuration that is related to this? Authentication still works fine for normal users as previously mentioned. My lemmy is running 0.16.7.

**Comment by bdonvr** [comment] 2023-07-05 04:25
> Just checked inspector, a 400 error is returned and then throws along with "Uncaught (in promise) password_incorrect". Same exact credentials authenticate successfully on the lemmy itself.
> 
> Tried the login on another iOS app and failed to authenticate only on the admin account for that as well.
> 
> Could just be something to do with my instance, is there some configuration that is related to this? Authentication still works fine for normal users as previously mentioned. My lemmy is running 0.16.7.

At a guess it could be because your instance is quite outdated.

**Comment by aeharding** [comment] 2023-07-15 16:12
Closing since I cannot reproduce

**Closed by aeharding** 2023-07-15 16:12 UTC
