### ISSUE TITLE
Disappearing reply window

### ISSUE THREAD

**Issue by ultratiem** [aeharding/voyager#542] opened 2023-07-28 16:05 UTC
This occurs in both the web app and iOS client.

After replying for the first time, the comment sheet disappears but still exists, allowing the user to type on the screen, yet much of the comment UI is missing.

Bug in action: https://github.com/aeharding/voyager/assets/2991193/c4f76930-6dbe-452e-b3c1-34d6a6ba794a

**Comment by aeharding** [comment] 2023-07-28 22:03
Hi there! I cannot reproduce. Please provide more information on your device version.

**Comment by aeharding** [comment] 2023-07-28 22:06
Also, closing as duplicate of #491, please provide more information for reproduction there instead. Thanks

**Closed by aeharding** 2023-07-28 22:06 UTC
Labels: reproduction-needed

**Comment by expresspotato** [comment] 2023-07-30 12:28
Hello,

It seems I'm experiencing the same bug. This actually can be reproduced simply going to the modal example in the ionic documentation, with an iOS 17 Beta 4 device found here: https://ionicframework.com/docs/api/modal?_gl=1*1l4bmzx*_ga*MTA2MzEyMzcwLjE2OTAyMTEwMTk.*_ga_REH9TJF6KF*MTY5MDcyMDAyMi4xNy4wLjE2OTA3MjAwMjIuMC4wLjA.
