### ISSUE TITLE
Crossposting in the app

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#955] opened 2023-11-19 17:08 UTC
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been properly implemented.

### What is the feature that you would like to have added?

The website gives the option to cross-post. It would be great to have that added to the app.

### Solution

We could have a button similar to the one on the website. 
![f2c679583394441e8a44cfa6b7477b9a](https://github.com/Memmy-App/memmy/assets/104597302/240cbb46-53dc-42a1-bd30-5c4ab15a222f)

### Alternatives

The way that I am doing it now is by copying the link of the post and going to the website on Safari to be able to perform cross-posting

**Comment by aeharding** [comment] 2023-11-19 18:47
Thanks, but this is a duplicate of #84

**Closed by aeharding** 2023-11-19 18:47 UTC
Labels: enhancement
