### ISSUE TITLE
Remove upvote/downvote buttons in post menu

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1154] opened 2024-01-11 18:23 UTC
**Is your feature request related to a problem? Please describe.**
Important buttons like crosspost and report are hidden and require a scroll because there are too many buttons in the menu

**Describe the solution you'd like**
It would be convenient if these buttons were displayed without needing to scroll and the upvote/downvote buttons are redundant since they're already present next to the menu button.

This is how it could look by default:

![image](https://github.com/aeharding/voyager/assets/114287507/df4120e2-624b-46e7-9545-5d2db8af8724)

**Comment by aeharding** [comment] 2024-01-19 00:25
Thanks, however this is a duplicate of https://github.com/aeharding/voyager/issues/417

**Closed by aeharding** 2024-01-19 00:25 UTC
Labels: enhancement
