### ISSUE TITLE
Add bottom nav functionality to comments view a la Boost/Sync

### ISSUE THREAD

**Issue by zandm7** [aeharding/voyager#634] opened 2023-08-09 20:34 UTC
Boost/Sync have a bottom nav UX that I really like; essentially it allows one to jump to the prev/next parent comment without needing to collapse the current thread. See the following image:

![Screenshot_20230809-142828~2](https://github.com/aeharding/voyager/assets/996428/08d3f861-271f-461d-a8dd-b8b15562ce94)

**Comment by aeharding** [comment] 2023-08-14 16:18
I believe this is a dupe of #384

**Closed by aeharding** 2023-08-14 16:18 UTC
