### ISSUE TITLE
[Bug] Page scrolls down, doesn't open on click

### ISSUE THREAD

**Issue by mdecourcy** [aeharding/voyager#352] opened 2023-07-10 02:50 UTC
Intermittent issue since 0.17.0 release. 

Environment: 

Android 13
PWA installed via [Vanadium Browser](https://github.com/GrapheneOS/Vanadium), a chromium fork.

![screen-20230709-193326](https://github.com/aeharding/wefwef/assets/49794076/d4ca01f2-3ef8-40e2-bc10-35a10d2cc757)

**Comment by aeharding** [comment] 2023-07-10 03:32
I believe this is a duplicate of #287. Please let me know if that doesn't sound right.

**Closed by aeharding** 2023-07-10 03:32 UTC
