### ISSUE TITLE
For iOS: Enable option to open links in external default browser instead of only in-app browser

### ISSUE THREAD

**Issue by debsidian** [aeharding/voyager#684] opened 2023-08-17 16:04 UTC
For native iOS app:

Currently when opening links, users only have the option of opening links in the in-app browser. Please enable the option for users to choose if they'd prefer to open links in the in-app browser or in their external default iOS browser. 

I'm aware that all iOS browsers are just skins of Safari, but there is additional benefit to allowing users the choice. For example, the Brave Browser iOS app has a built-in ad-blocker to the browser. 

Thank you for your consideration.

**Comment by aeharding** [comment] 2023-08-17 20:37
Thanks! This is a duplicate of #553. I'll be working on it shortly.

**Closed by aeharding** 2023-08-17 20:37 UTC
