### ISSUE TITLE
Filtered keywords are not saved

### ISSUE THREAD

**Issue by triglav-modular** [aeharding/voyager#919] opened 2023-11-10 12:24 UTC
**To Reproduce**

1. Go to Settings > Filters & Blocks
2. Add a keyword
3. Quit and relaunch the app
4. The filters are missing 

**Expected behavior**
I expect the filters to be persistent between sessions. 

**Smartphone:**

- Device: iPhone 14 Pro
- OS: iOS 17.2
- Version 1.22.0

**Comment by aeharding** [comment] 2023-11-10 14:13
Hi, thanks for the bug however I cannot reproduce. Is it possible you're viewing a different account?

**Comment by aeharding** [comment] 2024-01-28 16:59
Reproduction unavailable, so closing the ticket. Thanks!

**Closed by aeharding** 2024-01-28 16:59 UTC
Labels: bug, reproduction-needed
