### ISSUE TITLE
Touch is too sensitive while scrolling 

### ISSUE THREAD

**Issue by jonasisozen** [aeharding/voyager#726] opened 2023-09-09 22:18 UTC
Everytime I try scroll posts get randomly selected. No other app does this :/ 
My setup: nothing p
hone 1, android 13 and APK from github

**Comment by aeharding** [comment] 2023-09-22 17:53
Hi there! This is being tracked here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1474135

It's a chrome webview bug with momentum scrolling.

**Comment by aeharding** [comment] 2023-09-24 17:10
Closing as duplicate of #710

**Closed by aeharding** 2023-09-24 17:10 UTC
Labels: android, blocked
